//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RumahSakit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICAL_RECORD
    {
        public int MEDICAL_RECORD_ID { get; set; }
        public Nullable<int> PATIENT_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string COMPLAINT { get; set; }
    
        public virtual PATIENT PATIENT { get; set; }
    }
}
