//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RumahSakit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICINE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDICINE()
        {
            this.TRANSACTION_DETAIL = new HashSet<TRANSACTION_DETAIL>();
        }
    
        public int MEDICINE_ID { get; set; }
        public Nullable<int> TYPE_MEDICINE_ID { get; set; }
        public Nullable<int> ADMIN_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<System.DateTime> EXP { get; set; }
        public Nullable<int> STOCK { get; set; }
    
        public virtual ADMIN ADMIN { get; set; }
        public virtual TYPE_MEDICINE TYPE_MEDICINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACTION_DETAIL> TRANSACTION_DETAIL { get; set; }
    }
}
