//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RumahSakit.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_RS_SINGGIHEntities1 : DbContext
    {
        public DB_RS_SINGGIHEntities1()
            : base("name=DB_RS_SINGGIHEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<DOCTOR> DOCTORs { get; set; }
        public virtual DbSet<MEDICAL_RECORD> MEDICAL_RECORD { get; set; }
        public virtual DbSet<MEDICINE> MEDICINEs { get; set; }
        public virtual DbSet<NURSE> NURSEs { get; set; }
        public virtual DbSet<PATIENT> PATIENTs { get; set; }
        public virtual DbSet<POLY> POLies { get; set; }
        public virtual DbSet<ROOM> ROOMs { get; set; }
        public virtual DbSet<SCHEDULE> SCHEDULEs { get; set; }
        public virtual DbSet<SCHEDULE_NURSE> SCHEDULE_NURSE { get; set; }
        public virtual DbSet<SPECIALIST> SPECIALISTs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TRANSACTION> TRANSACTIONs { get; set; }
        public virtual DbSet<TRANSACTION_DETAIL> TRANSACTION_DETAIL { get; set; }
        public virtual DbSet<TYPE_MEDICINE> TYPE_MEDICINE { get; set; }
        public virtual DbSet<TYPE_POLY> TYPE_POLY { get; set; }
        public virtual DbSet<TYPE_ROOM> TYPE_ROOM { get; set; }
    }
}
