//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RumahSakit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PATIENT()
        {
            this.MEDICAL_RECORD = new HashSet<MEDICAL_RECORD>();
            this.TRANSACTIONs = new HashSet<TRANSACTION>();
        }
    
        public int PATIENT_ID { get; set; }
        public Nullable<int> ADMIN_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> BIRTH { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public Nullable<int> AGE { get; set; }
        public string GENDER { get; set; }
        public Nullable<int> STATUS { get; set; }
    
        public virtual ADMIN ADMIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICAL_RECORD> MEDICAL_RECORD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACTION> TRANSACTIONs { get; set; }
    }
}
