//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RumahSakit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_POLY
    {
        public int TYPE_POLY_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<int> POLY_ID { get; set; }
    
        public virtual POLY POLY { get; set; }
    }
}
